name: 'SSG Publish Drafts'
description: 'Publish drafts with a date greater than the current time'
author: 'one-aalam'
branding:
  icon: 'calendar'
  color: 'purple'
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  github_actor:
    description: 'The Github actor to use'
    required: true
  github_repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'main'
  site_path:
    description: 'Directory containing the SSG root folder.'
    required: false
    default: '.'
  site_drafts_dir:
    description: 'Directory containing all the drafts in *.md format.'
    required: false
    default: 'src/drafts'
  site_published_dir:
    description: 'Directory to contain all the published content in *.md format.'
    required: false
    default: 'src/pages/blog'
runs:
  using: 'node12'
  main: 'dist/index.js'
